### ISSUE TITLE
TCPDF 6.2.22 and later breaks multi usage of the same image

### ISSUE THREAD

**Issue by chilek** [tecnickcom/TCPDF#153]
As in subject. All versions prior to 6.2.21 are not affected.
From 6.2.22 when you use the same image many times in your pdf only first appearance is supported properly. All following links to the same image are not visible/broken.
In my opinion code from TCPDF::_destroy() should not always delete images stored in cache located at K_PATH_CACHE setting. If you need more info please let me know.

Related to https://github.com/Dolibarr/dolibarr/issues/11651

**Comment by nicolaasuni** [comment]
This should be fixed in the latest version.

**Comment by chilek** [comment]
@nicolaasuni could you provide info which commit fixes it?

PS. Did you think about github sponsor program application? I'd be one of first sponsors to reward the great job you do! My plan is 10$ / month for your project.

**Comment by chilek** [comment]
Tested with 6.3.5 - problem persists!

**Comment by interduo** [comment]
@nicolaasuni did You fix that issue?

**Comment by paszczus** [comment]
Hello,
any update with this? Please...
