### ISSUE TITLE
unlink() No such file or directory warning on 6.3.2

### ISSUE THREAD

**Issue by kuz1toro** [tecnickcom/TCPDF#159]
hello after updating to tcpdf 6.3.2 i get warning on method tcpdf.php line 7801 with message " unlink(..\..\...\temp/__tcpdf_393737b5201efd77eec80f86fca55b63_imgmask_alpha_af7077161af0ed4509f4b792149d0a9a)" No such file or directory

after commenting out that line, the issue gone....
i hope theres a better fix for this

**Comment by dduers** [comment]
Hello, thanks for the library!

I can confirm this problem.
It seams to be related to pdf files that include graphics, when tcpdf class tries to unlink an unexistent temporary file.

`unlink(C:\xampp\tmp/__tcpdf_3a46767c57fb621130de3fd07a3df1e0_imgmask_alpha_cfa558e0c9ec44149b0310ce46a8ae62): No such file or directory`

The file really does not exist.
The error exists for my Windows dev environment and also for the unix based production environment.

```
[C:/xampp/htdocs/domain3.local/vendor/tecnickcom/tcpdf/tcpdf.php:7801] unlink()
[C:/xampp/htdocs/domain3.local/vendor/tecnickcom/tcpdf/tcpdf.php:2022] TCPDF->_destroy()
[C:/xampp/htdocs/domain3.local/vendor/tecnickcom/tcpdf/tcpdf.php:7822] TCPDF->__destruct()
[C:/xampp/htdocs/domain3.local/vendor/tecnickcom/tcpdf/tcpdf.php:3007] TCPDF->_destroy()
[C:/xampp/htdocs/domain3.local/vendor/tecnickcom/tcpdf/tcpdf.php:7585] TCPDF->Close()
[C:/xampp/htdocs/domain3.local/app/classes/model/bill.php:503] TCPDF->Output()
[C:/xampp/htdocs/domain3.local/app/classes/controller/order.php:671] classes\model\bill->createBillTcPdf()
[C:/xampp/htdocs/domain3.local/app/classes/controller/order.php:120] classes\controller\order->createBillPDF()
```

When uncommenting the line `7794` in `tcpdf.php` everything works fine.
![tcpdf_hack](https://user-images.githubusercontent.com/44911486/71807508-bf757000-306b-11ea-86f8-30f81251523e.png)

Regards,
Daniel

**Comment by piRGoif** [comment]
I ran into the same issue...
There are 2 PR that seems to address this : #142, #145

**Comment by markusramsak** [comment]
I have the same issue. Simply adding an @ before unlink call solves the issue

**Comment by santaclaus21** [comment]
I have got the same problem when I use image...
$pdf->Image(__DIR__.'/img/jordan_logo_200.png', 10, $pdf->GetY(), 50, '', '', 'https://jordan.pl', '', false, 300);

**Comment by bretto36** [comment]
I'm getting this when added a base64 image 

<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAa4AAABwCAYAAABGtpRxAAAAGXRFWHRTb2Z0d2FyZ....

**Comment by nicolaasuni** [comment]
This should be fixed in the latest version.
