### ISSUE TITLE
Notice: Trying to access array offset on value of type int

### ISSUE THREAD

**Issue by Necklaces** [tecnickcom/TCPDF#167]
Running example 59 in php 7.4:

```
php example_059.php
```

gives me this:

```
PHP Notice:  Trying to access array offset on value of type int in /home/user/TCPDF/tcpdf.php on line 12385
```

it seems to happen here:

```
$pdf->addHTMLTOC(1, 'INDEX', $bookmark_templates, true, 'B', array(128,0,0));
```

Would be nice if there was a workaround or a fix..

**Comment by desarrolloBersoft** [comment]
In the new versions of php it doesn´t take the value of an variable like an array, and when you check the tcpdf file the setLink and the addTOC functions you will find a line where it is making a comparacion with page[0] == *, that´s the error. 
I changed the line to 
// if (!empty($page) AND ($page[0] == '*')) {
if (!empty($page) AND (strpos($page,"*"))) {
It worked.
