### ISSUE TITLE
syntax error: unexpected '[' in tcpdf.php on line 12387

### ISSUE THREAD

**Issue by tganudev71** [tecnickcom/TCPDF#176]
line 12387
if ((string)$page && (((string)$page)[0] == '*')) {
   $page = intval(substr($page, 1));
   // this page number will not be changed when moving/add/deleting pages
   $fixed = true;
}

**Comment by bolduz** [comment]
Same here, happened only recently.

File: `vendor/tecnickcom/tcpdf/tcpdf.php`, line 12387

A simple solution would be splitting the cast and the checks:

```php
$pageAsString = (string) $page;
if ($pageAsString && $pageAsString[0] == '*') {
```
