### ISSUE TITLE
PHP7.3, A non-numeric value encountered

### ISSUE THREAD

**Issue by marlboroman3** [tecnickcom/TCPDF#185]
With latest clone today ...

Severity: Warning
Message: A non-numeric value encountered
Filename: tcpdf/tcpdf.php
Line Number: 5398

Seems `$this->textstrokewidth` is FALSE, fails in a multiplication.

Setting it to 0 in this case doesn't break anything for me.

**Comment by nicolaasuni** [comment]
I s this now fixed?

**Comment by d-salerno** [comment]
this seems to still happen. I'm not sure where `$this->textstrokewidth` is being set, but inside the function `getCellCode` it is non numeric. Something like:
```
if(!is_numeric($this->textstrokewidth)){
   $this->textstrokewidth = 0;
}
$s .= sprintf('BT %d Tr %F w ET ', $this->textrendermode, ($this->textstrokewidth * $this->k));
```
fixes the issue.

**Comment by d-salerno** [comment]
sure, here's the PR: [627](https://github.com/tecnickcom/TCPDF/pull/627)
