### ISSUE TITLE
Replace core PDF font

### ISSUE THREAD

**Issue by alcinovanrooyen** [tecnickcom/TCPDF#203]
Hi,

I'm trying to replace the core font Times New Roman, some Polish glyphs are missing in the current version of the font.

Is it perhaps possible and if so, how ?

**Comment by SuperVirus** [comment]
Short answer: NO.
Long answer:
The Standard 14 Fonts (*) are part of the PDF viewer or the operating system and are not included in the generated PDF file itself. To support more / other glyphs it would be neccessary to modify the client systems, on wich the PDF is viewed.

You can of course use (almost) any other font.
The font can be embedded in the PDF or must be available on the viewer's computer.
If you embed the font (or a subset), the generated file will be much larger and you need the appropriate license rights - however the viewer does not need the font in this case.


---------------------------
(*) Standard 14 Fonts:
- Courier / Courier Bold / Courier Oblique / Courier Bold-Oblique
- Helvetica / Helvetica Bold / Helvetica Oblique / Helvetica Bold-Oblique
- Times Roman / Times Bold / Times Italic / Times Bold-Italic
- Symbol
- Zapf Dingbats

**Comment by alcinovanrooyen** [comment]
Understood, thank you.
