### ISSUE TITLE
PHP 8 deprecations

### ISSUE THREAD

**Issue by williamdes** [tecnickcom/TCPDF#222]
```
PHP Deprecated:  Required parameter $currentfont follows optional parameter $isunicode in vendor/tecnickcom/tcpdf/include/tcpdf_fonts.php on line 1998

Deprecated: Required parameter $currentfont follows optional parameter $isunicode in vendor/tecnickcom/tcpdf/include/tcpdf_fonts.php on line 1998
PHP Deprecated:  Required parameter $currentfont follows optional parameter $isunicode in vendor/tecnickcom/tcpdf/include/tcpdf_fonts.php on line 2024

Deprecated: Required parameter $currentfont follows optional parameter $isunicode in vendor/tecnickcom/tcpdf/include/tcpdf_fonts.php on line 2024
PHP Deprecated:  Required parameter $currentfont follows optional parameter $setbom in vendor/tecnickcom/tcpdf/include/tcpdf_fonts.php on line 2040

Deprecated: Required parameter $currentfont follows optional parameter $setbom in vendor/tecnickcom/tcpdf/include/tcpdf_fonts.php on line 2040
PHP Deprecated:  Required parameter $currentfont follows optional parameter $setbom in vendor/tecnickcom/tcpdf/include/tcpdf_fonts.php on line 2060

Deprecated: Required parameter $currentfont follows optional parameter $setbom in vendor/tecnickcom/tcpdf/include/tcpdf_fonts.php on line 2060
PHP Deprecated:  Required parameter $currentfont follows optional parameter $str in vendor/tecnickcom/tcpdf/include/tcpdf_fonts.php on line 2077

Deprecated: Required parameter $currentfont follows optional parameter $str in vendor/tecnickcom/tcpdf/include/tcpdf_fonts.php on line 2077
PHP Deprecated:  Required parameter $currentfont follows optional parameter $str in vendor/tecnickcom/tcpdf/include/tcpdf_fonts.php on line 2093

Deprecated: Required parameter $currentfont follows optional parameter $str in vendor/tecnickcom/tcpdf/include/tcpdf_fonts.php on line 2093
PHP Deprecated:  Required parameter $tagvspaces follows optional parameter $default_css in vendor/tecnickcom/tcpdf/include/tcpdf_static.php on line 1139

Deprecated: Required parameter $tagvspaces follows optional parameter $default_css in vendor/tecnickcom/tcpdf/include/tcpdf_static.php on line 1139
PHP Deprecated:  Required parameter $k follows optional parameter $points in vendor/tecnickcom/tcpdf/include/tcpdf_static.php on line 2510

```

https://travis-ci.org/github/phpmyadmin/phpmyadmin/jobs/682827038#L347

**Comment by brainfoolong** [comment]
Hi, this issues should be fixed with this pull request -> https://github.com/tecnickcom/TCPDF/pull/244

**Comment by williamdes** [comment]
https://github.com/tecnickcom/TCPDF/pull/244

**Comment by williamdes** [comment]
Hello @nicolaasuni 
Could you merge the fix for this issue, PHP 8 is out now :)
Thank you, let me know if you need some help on maintenance for this repository.

**Comment by fibis** [comment]
It would be great, when this problem will be resolved soon!

**Comment by atomkind** [comment]
would love to see it solved too, just upgraded to PHP8 today and only tcpdf deprecations left to solve 👍

**Comment by williamdes** [comment]
@nicolaasuni could you release the latest fixes please ?

**Comment by kacperpodgajny** [comment]
I would also like to kindly ask for these changes to be released sometime soon

**Comment by ajtsch** [comment]
Indeed that would be nice !

**Comment by jwegner** [comment]
That would be awesome :)

**Comment by atomkind** [comment]
well, i've seen the important notice:

> IMPORTANT
> 
> A new version of this library is under development at [https://github.com/tecnickcom/tc-lib-pdf](https://github.com/tecnickcom/tc-lib-pdf) and as a consequence this version will not receive any additional development or support. This version should be considered obsolete, new projects should use the new version as soon it will become stable.

But this linked project i still not stable released.
So my thoughts are - this won't be supported anymore and the new project is not released... try to swap this function-params by my self!

So i did it, had some more of the `PHP Deprecated:` notices and now, i get an `fatal error` ...
(and dont know how to fix it)

> [26-Jan-2021 16:04:24 CET] PHP Fatal error:  Uncaught TypeError: Cannot access offset of type string on string in /tcpdf/include/tcpdf_fonts.php:2645
Stack trace:
> 0 /tcpdf/include/tcpdf_fonts.php(2078): TCPDF_FONTS::utf8Bidi(Array, '{{:ptp:}}', false, true, true)
> 1 /tcpdf/include/tcpdf_fonts.php(2061): TCPDF_FONTS::utf8StrArrRev(Array, '{{:ptp:}}', false, false, true)
> 2 /tcpdf/tcpdf.php(7849): TCPDF_FONTS::utf8StrRev('{{:ptp:}}', Array, false, false, true)
> 3 /tcpdf/tcpdf.php(7866): TCPDF->getInternalPageNumberAliases('{:ptp:}')
> 4 /tcpdf/tcpdf.php(7931): TCPDF->getAllInternalPageNumberAliases()
> 5 /tcpdf/tcpdf.php(9982): TCPDF->_putpages()
> 6 /tcpdf/tcpdf.php(3005): TCPDF->_enddoc()
> 7 /tcpdf/tcpdf.php(7574): TCPDF->Close()

The functions i used:
> 8 ...: TCPDF->Output('', 'S')
> 9 ....: htmlToPdf('...html string....', 'Antrag')
>  thrown in /tcpdf/include/tcpdf_fonts.php on line 2645

I attach the changed TCPDF files to this comment, maybe someone know how to fix this error? I just swaped the required parameters with the optional parameters, nothing else!

[tcpdf.zip](https://github.com/tecnickcom/TCPDF/files/5874241/tcpdf.zip)

**Comment by williamdes** [comment]
Ha this warning was written 6 years ago 
https://github.com/tecnickcom/TCPDF/commit/009f2304c3a9c8152b89a5321a8825f250911dc3

Just use the last commit on the composer version for now :)

**Comment by atomkind** [comment]
Do i understand right, we should use the version 6.2.13? Or 6.2.26?
(and change the deprecation function params again?)
Or just the composer.json file of the older version?

Sorry, this is how i understand your comment 
...confused

**Comment by williamdes** [comment]
Hi everybody
If you are using composer you can use the same changes that I have done for phpMyAdmin.
See: https://github.com/phpmyadmin/phpmyadmin/pull/16596 :heavy_check_mark: 

```diff
-        "tecnickcom/tcpdf": "^6.3",
+        "tecnickcom/tcpdf": "dev-main#456b794f1fae9aee5c151a1ee515aae2aaa619a3",
```

Or using a less secure way without specifying a particular commit: https://packagist.org/packages/tecnickcom/tcpdf#dev-main
But this alternative will not be future proof :warning: 


```diff
-        "tecnickcom/tcpdf": "^6.3",
+        "tecnickcom/tcpdf": "dev-main",
```

**Comment by Shakil-Shahadat** [comment]
I changed that line and then try `composer update`. But it gave me the following errors
```
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires php ^7.1.3 but your php version (8.0.0) does not satisfy that requirement.
  Problem 2
    - Root composer.json requires phpmyadmin/coding-standard ^1.0 -> satisfiable by phpmyadmin/coding-standard[1.0].
    - phpmyadmin/coding-standard 1.0 requires php ^7.1 -> your php version (8.0.0) does not satisfy that requirement.
  Problem 3
    - phpmyadmin/sql-parser[5.0.0, ..., 5.4.1] require php ^7.1 -> your php version (8.0.0) does not  satisfy that requirement.
    - Root composer.json requires phpmyadmin/sql-parser ^5.0 -> satisfiable by phpmyadmin/sql-parser [5.0.0, ..., 5.4.1].
```
I tried `composer selfupdate`, it said `You are already using composer version 2.0.8 (stable channel).`.

What should I do now?

Thanks.

**Comment by Shakil-Shahadat** [comment]
Found the solution. Also need to change the following lines in composer.json,

Line 41: `"php": "^7.1.3",` to `"php": "^7.1.3 || ^8.0",`
Line 51: `"phpmyadmin/sql-parser": "^5.0",` to `"phpmyadmin/sql-parser": "dev-master#d412f7ac1a0a5833072c0e0def14674f39a1bdea",`
Line 84: `"php-webdriver/webdriver": "^1.7.1",` to `"php-webdriver/webdriver": "^1.9",`
Line 85: `"phpmyadmin/coding-standard": "^1.0",` to `"phpmyadmin/coding-standard": "^2.1.1",`
Line 86: `"phpstan/phpstan": "^0.11.5",` to `"phpstan/phpstan": "^0.12.64",`

Changed only things I had to change according to [latest composer](https://github.com/phpmyadmin/phpmyadmin/blob/master/composer.json) or higher when that didn't work, nothing else. Also, had to turn on the PHP curl extension.

**Comment by atomkind** [comment]
I am not using composer, i simply download the files, upload to my host, require_once the tcpdf.php and use the class.

Can't update with any command, need the files to down- and upload.
I would love to get a link or description, where i can download the files... sorry :P

**Comment by Shakil-Shahadat** [comment]
@atomkind after downloading, change the composer file to the one I provided and then follow the instruction I provided in the gist comment. After that, you can upload it to your host. Or you can wait for the next release.

**Comment by williamdes** [comment]
You can download the code from the web UI at https://github.com/tecnickcom/TCPDF (green "code :arrow_down:" button)

Aka: https://github.com/tecnickcom/TCPDF/archive/main.zip (same as dev-main)

For phpMyAdmin issues please do not comment here, and be sure to use phpMyAdmin 5.0 or a later version.

**Comment by atomkind** [comment]
This is not a phpmyadmin issue.
I downloaded it, opened the composer.json file and it looks different, there is no line with `"tecnickcom/tcpdf"` that i could change from versionnumber to do `dev#main` or `dev-main#456b794f1fae9aee5c151a1ee515aae2aaa619a3`
Even if i chnge the versionnumber line
from `  "version": "6.3.5",`
to `  "version": "dev-main#456b794f1fae9aee5c151a1ee515aae2aaa619a3",`
Its not working.. sorry

>  {
  "name": "tecnickcom/tcpdf",
  "version": "6.3.5",
  "homepage": "http://www.tcpdf.org/",
  "type": "library",
  "description": "TCPDF is a PHP class for generating PDF documents and barcodes.",
  "keywords": [
    "PDF",
    "tcpdf",
    "PDFD32000-2008",
    "qrcode",
    "datamatrix",
    "pdf417",
    "barcodes"
  ],
  "license": "LGPL-3.0-only",
  "authors": [
    {
      "name": "Nicola Asuni",
      "email": "info@tecnick.com",
      "role": "lead"
    }
  ],
  "require": {
    "php": ">=5.3.0"
  },
  "autoload": {
    "classmap": [
      "config",
      "include",
      "tcpdf.php",
      "tcpdf_parser.php",
      "tcpdf_import.php",
      "tcpdf_barcodes_1d.php",
      "tcpdf_barcodes_2d.php",
      "include/tcpdf_colors.php",
      "include/tcpdf_filters.php",
      "include/tcpdf_font_data.php",
      "include/tcpdf_fonts.php",
      "include/tcpdf_images.php",
      "include/tcpdf_static.php",
      "include/barcodes/datamatrix.php",
      "include/barcodes/pdf417.php",
      "include/barcodes/qrcode.php"
    ]
  }
}

**Comment by Shakil-Shahadat** [comment]
You are supposed to make those changes to `composer.json` of phpmyadmin.

**Comment by williamdes** [comment]
> You are supposed to make those changes to `composer.json` of phpmyadmin.

Exactly!

If you downloaded tcpdf code you have nothing more to do, you already have the code.

**Comment by atomkind** [comment]
oh crap.. i dont know how to access this file.
The host is just a simple web-host (strato...) and im shure not allowed to change anything in phpmyadmin..
Now i feel dumb

**Comment by williamdes** [comment]
> oh crap.. i dont know how to access this file.
> The host is just a simple web-host (strato...) and im shure not allowed to change anything in phpmyadmin..
> Now i feel dumb

Next 5.1 release will contain the fix, hope they will upgrade onto it. But you can open a ticket and let them know they should use php 7 until next 5.1 version.

**Comment by atomkind** [comment]
just in case there is anybody interested,
my host (strato) answered to my question if they will update phpMyAdmin soon (they run v.4.9.2) after 5 days:
> they cannot provide more detailed information on the processing status before a function is published. As soon as the functions are implemented, there will be information on this. 
or i can buy a server package.

But still... why do i have to update phpMyAdmin when i just want to use TCPDF in PHP8... this souldnt be related, or?

**Comment by Shakil-Shahadat** [comment]
@atomkind I installed phpmyadmin to my shared hosting once and it went very smoothly, cause I wanted to use the latest version. You can try that too.

Anyway, that discussion is out of the scope of this post.

**Comment by marufmax** [comment]
Using 6.3 version and PHP 8 still getting this

**Comment by atomkind** [comment]
(still don't know why phpMyAdmin is required for a pdf extension)

**Comment by williamdes** [comment]
> (still don't know why phpMyAdmin is required for a pdf extension)

It is not :)
phpMyAdmin can have a PDF extension if you have tcpdf installed in phpMyAdmin.

**Comment by atomkind** [comment]
But comments above tell me i have to change composor.json of phpMyAdmin and i am not able to do this.

**Comment by williamdes** [comment]
> But comments above tell me i have to change composor.json of phpMyAdmin and i am not able to do this.

This was for users using phpMyAdmin, you can apply https://github.com/tecnickcom/TCPDF/issues/222#issuecomment-767849136 to any php project using composer

**Comment by atomkind** [comment]
I realy dont understand what is going on and gettin frustrated at a point..
The TCPDF-Lib is not longer supported and there is an other lib, called tc-lib-pdf - this is also not ready to use.
PHP 8 is out since a while and Nothing released to use TCPDF (or so..) and all issues and comments in here say something about composer .... i still dont know or understand what this is, i dont use it. I need the PDF-Lib as PHP-Class in my website to create PDF and this is the only thing missing, to upgrade to PHP 8.
There is no release on TCPDF or tc-lib-pdf, to work in php8, right? There is just a issue-comment of elibby/tcpdf-laravel that say `this is a problem of TCPDF, not of elibby/tcpdf-laravel` .

.. soooo there is still no functional release of PDF-lib to use in PHP8?
(sorry for being upsessed, realy dont wanna be)

**Comment by Shakil-Shahadat** [comment]
@atomkind Just update your phpmyadmin to 5.1.0 if you don't understand anything else. That version doesn't have that problem.

**Comment by atomkind** [comment]
like i said, i can't.
I run on a simple host, nothing fancy. So i can't change anything on phpmyadmin and i realy dont want to install my own, just for using tcpdf .. (this is where my last question came in place - why do i have to install phpmyadmin when i want to use tcpdf?)

**Comment by williamdes** [comment]
First there is no phpMyAdmin to update if you have not heard about phpMyAdmin.

Second if you have not heard about composer then ignore the composer comments.

Third if you have not heard about composer then go to the homepage of this repository and download the code (aka un-released code, just like a released version) (https://github.com/tecnickcom/TCPDF/archive/main.zip)

And finally the repository seems not maintained, this is bad, very bad because it is the "only" pdf lib that everyone uses.
And the other lib is not ready and not usable.

That said I will probably fork this and maintain it in @code-lts some day soon

**Comment by mstyles** [comment]
A revived fork would be wonderful! :heart:  If you do end up doing that, @williamdes, would you mind mentioning so in here? I'd be happy to switch over

**Comment by theroch** [comment]
An alternative is https://github.com/mpdf/mpdf which supports PHP 8.0 and is well maintained.
But you have to reimplement your PDF logic.
The other alternative is to fork TCPDF like @williamdes mentioned.

**Comment by atomkind** [comment]
@williamdes thank you :-*

**Comment by williamdes** [comment]
I forked the project as `WarnockPDF`.
Please go to https://github.com/code-lts/WarnockPDF/discussions and start asking questions and share your ideas and features you would need.
I intend to launch a release as soon as possible when all the lights are green.

Please do not discuss about this here, go to WarnockPDF discussions ;)

**Comment by ANSB** [comment]
If you use TCPDF, this means you know how to use PHP... Under PHP8 you'll find mainly 2 problems which are easy to solve editing TCPDF code;
1) cruly braces. That's the fact is was possible to use {} in order to access value in an array like $data{1}. You'll find 3 or 4 like that in TCPDF code. Just change them by classic []. So $data{1} must be changed to $data[1].
2) optinal parameter. In PHP you can call a function sending (eg) 2 parameters when the declaration of the function as 3 or more. Before PHP8 it was not necessary to add a default value for the "missing parameters". So :
function test($a,$b,$c);
the call it with:
test('hello');
was possible. It's not yet the case. You must have default values in the declaration so:
function test($a,$b='',$c=''); for example.
This is the "Required parameter" error.

Notice another point: in tcpdf_font, you'll find a function name unichr. In some case it received $c as string. You can solve this adding $c = (int)$c; as first line of the function.
I use TCPDF in my PHP8.03 web site, and everything is fine.

Hope this help

**Comment by williamdes** [comment]
6.4.1 is out https://github.com/tecnickcom/TCPDF/releases/tag/6.4.1

**Comment by eugenio11** [comment]
Hi! For some reason, the file tcpdf.php in the latest version (I guess 6.4.2) still have in the heading
// Version     : 6.3.2
// Begin       : 2002-08-03
// Last Update : 2019-09-20
I think this is mistake, am I right?

**Comment by williamdes** [comment]
> Hi! For some reason, the file tcpdf.php in the latest version (I guess 6.4.2) still have in the heading
> // Version : 6.3.2
> // Begin : 2002-08-03
> // Last Update : 2019-09-20
> I think this is a mistake, am I right?

Yes, the headers are not up to date

**Comment by eugenio11** [comment]
> > Hi! For some reason, the file tcpdf.php in the latest version (I guess 6.4.2) still have in the heading
> Yes, the headers are not up to date

thanks!
