### ISSUE TITLE
Empty result for big reports with writeHTML()

### ISSUE THREAD

**Issue by eisberg** [tecnickcom/TCPDF#267]
The error was noticed 10 years ago. When trying to generate a PDF from a large HTML file, an empty file is generated, and no error messages are generated.

The report generation dies because of a preg_replace() used by TCPDF. It was a PHP bug for older versions (mine is 5.3.3), preg_replace() returns null silently when the string is too long. See this:

https://sourceforge.net/p/tcpdf/discussion/435311/thread/f7f96b04/
https://stackoverflow.com/questions/14870397/tcpdf-displays-blank-pdf-if-query-result-is-big

**Comment by skillbox-koutja** [comment]
I have same problem

**Comment by singhsanjay5151** [comment]
> I have same problem

have you solved it if yes then how???

**Comment by koutja** [comment]
> > I have same problem
> 
> 
> 
> have you solved it if yes then how???

Yes. Fix was merged
