### ISSUE TITLE
How to make "border-radius" work?

### ISSUE THREAD

**Issue by KonstantinKolodnitsky** [tecnickcom/TCPDF#285]
I need a rect to be like that:
<img width="264" alt="Screen Shot 2020-09-18 at 1 01 33 pm" src="https://user-images.githubusercontent.com/2089543/93550712-52aec580-f9af-11ea-8519-21f9202763ef.png">

Is there a way to accomplish this?

**Comment by NiklasBr** [comment]
You can't accomplish this with CSS in TCPDF, but you could draw an SVG to achieve the same result.
