### ISSUE TITLE
"continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?

### ISSUE THREAD

**Issue by macJames976** [tecnickcom/TCPDF#316]
Hi,
on PHP 7.3.23 (not 7.3.22) i receive this error message:

"continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?

on tcpdf.php: line 17786

Any ideas?

**Comment by speleo3** [comment]
Looks like this was fixed in https://github.com/tecnickcom/TCPDF/pull/91

**Comment by macJames976** [comment]
yes
