### ISSUE TITLE
PHP 8 compatible release

### ISSUE THREAD

**Issue by aimeos** [tecnickcom/TCPDF#318]
When do you plan to tag a new release which contains the fixes for PHP 8 in dev-main?
TCPDF is the last package that prevents us from fully supporting PHP 8 at the moment.

**Comment by sgiehl** [comment]
That would be awesome. The main branch actually already should be compatible with PHP 8. 
But requiring a specific commit in composer isn't that handsome...

**Comment by aimeos** [comment]
@nicolaasuni Can we speed up a PHP 8 compatible release with a donation? :-)

**Comment by candidodmv** [comment]
I'm running this current code on PHP 8.0.1 like a charm

**Comment by linzening** [comment]
Please make a new tag,for php8.0,thanks.

**Comment by jansor** [comment]
@nicolaasuni Any idea when we can expect a new release for PHP8.0

**Comment by interduo** [comment]
Hi @nicolaasuni are You planing to release tcpdf with php8 support in 2021Q1/2021Q2?

**Comment by mstyles** [comment]
I'm using this:
```
"tecnickcom/tcpdf": "dev-main#456b794f1fae9aee5c151a1ee515aae2aaa619a3 as 6.3.6"
```
But as @sgiehl mentioned, it'd be preferable if there was an actual tag, particularly for those for whom this isn't a direct dependency and otherwise wouldn't need to include it in the `composer.json` at all.

**Comment by nicolaasuni** [comment]
All pending PRs were merged today.
Note that the new library tc-lib-pdf is already PHP8 compatible even if unfinished.

**Comment by interduo** [comment]
@nicolaasuni 
Does current state of tc-lib-pdf replace TCPDF fully?

Have You got any function comparision between them or some TODO list for tc-lib-pdf?

**Comment by CarloFoc** [comment]
Is there a version of tcpdf which is fully compatible with php 8?
if so, can you provide a link to download it as a zip file?

**Comment by williamdes** [comment]
> Is there a version of tcpdf which is fully compatible with php 8? if so, can you provide a link to download it as a zip file?

https://github.com/tecnickcom/TCPDF/releases/tag/6.6.2

Yes, we test up to PHP 8.2. phpMyAdmin and many other tools use recent TCPDF versions with PHP 8.
In Debian we have PHP 8 for TCPDF and stuff. Everything is going well
