### ISSUE TITLE
[php8] Required parameter $currentfont follows optional parameter $isunicode

### ISSUE THREAD

**Issue by Maks3w** [tecnickcom/TCPDF#321]
```
Required parameter $currentfont follows optional parameter $isunicode

/xxx/vendor/tecnickcom/tcpdf/include/tcpdf_fonts.php:1998
```

The method signature is `public static function UTF8StringToArray($str, $isunicode=true, &$currentfont)`

This situation is not unique to this method. There are more methods in the file with the pass-by-reference argument after optionals

**Comment by williamdes** [comment]
Already fixed :)
But still no release, see: #222

**Comment by williamdes** [comment]
Duplicate of #222
