### ISSUE TITLE
Please make a new tag

### ISSUE THREAD

**Issue by linzening** [tecnickcom/TCPDF#324]
Please make a new tag,for php8.0,thanks.

**Comment by jansor** [comment]
@nicolaasuni Any idea when we can expect a new release for PHP8.0

**Comment by mstyles** [comment]
this is a duplicate of https://github.com/tecnickcom/TCPDF/issues/318

**Comment by nicolaasuni** [comment]
I have merged today all pending PRs.
Please consider contributing to https://github.com/tecnickcom/tc-lib-pdf
