### ISSUE TITLE
Last version 6.3.5  composer

### ISSUE THREAD

**Issue by Peterbins** [tecnickcom/TCPDF#334]
On site  composer : https://packagist.org/packages/tecnickcom/tcpdf#6.3.5    is last update  2020-02-14 14:20 UTC
when can i expect an update.

**Comment by Peterbins** [comment]
When i use tecnickcom/tcpdf": "dev-main",  it works on PHP no warnings

**Comment by nicolaasuni** [comment]
I have released a new 6.4.0 tag today.
