### ISSUE TITLE
6.4.1 - hr bug if no style

### ISSUE THREAD

**Issue by ANSB** [tecnickcom/TCPDF#347]
**Undefined array key "style" in /xxxx/tcpdf.php on line 18924**
It's about hr tag. We can "style" it but when there is no style, we get and undefined array ($tag['style']['cap'], and next). A test using isset (like with $tag['height']) is required.

_Note: if you don't want to wait for update, juste add:
hr {
	cap:'';
	join:'';
	dash:'';
	phase:'';
}
on your html code and you'll get "basic HR"_

**Comment by williamdes** [comment]
I made a fix for it: https://github.com/tecnickcom/TCPDF/pull/350

**Comment by yii2backendwebdeveloper** [comment]
This has not been fixed yet.

**Comment by TimothyRichardGreen** [comment]
Until the pull request above is merged, does anyone have suggestions on how to work around this? Adding a style tag doesn't seem to help.

https://stackoverflow.com/q/67024224/209139

**Comment by stchr** [comment]
As far as I can see this is fixed with 7ecf638b13ed35cd87146c9b8333d7c879d4044d in #348.
@nicolaasuni could we please get a new version released? Thx!

**Comment by stchr** [comment]
@ANSB This is fixed now with 6.4.2, can you close this issue?
