### ISSUE TITLE
中文文件名无效？

### ISSUE THREAD

**Issue by shunhua** [tecnickcom/TCPDF#354]
中文文件名无效？

**Comment by adiatma85** [comment]
Excuse me, could you type it in english?
Thank you

**Comment by shunhua** [comment]
> Excuse me, could you type it in english?
> Thank you

Excuse me, could you type it in Chinese?
Thank you

**Comment by adiatma85** [comment]
使用Google翻译后，我知道您的意思了。 据我所知，该软件包尚不支持普通话
（抱歉，如果不准确，因为我个人使用的是Google翻译）

**Comment by shunhua** [comment]
> 使用Google翻译后，我知道您的意思了。 据我所知，该软件包尚不支持普通话
> （抱歉，如果不准确，因为我个人使用的是Google翻译）

likewise，Thanks.

**Comment by pierresh** [comment]
Check this link, it works well even with PHP 8 and the latest version of TCPDF

https://alucard-blog.blogspot.in/2013/06/tcpdf-how-to-display-chinese-character.html
