### ISSUE TITLE
PHP 8.1 - getGDgamma does not return int

### ISSUE THREAD

**Issue by williamdes** [tecnickcom/TCPDF#401]
```
 Implicit conversion from float 4.369562793149873 to int loses precision in /home/runner/work/TCPDF/TCPDF/tcpdf.php on line 7360
```

On PHP 8.1 CI

**Comment by cappadaan** [comment]
also on other lines (4179 + 4180)

 Implicit conversion from float 1.0787944444444442 to int loses precision on line 4180 in /httpdocs/vendor/tecnickcom/tcpdf/tcpdf.php
