### ISSUE TITLE
setHeaderData asks for string lw

### ISSUE THREAD

**Issue by gemal** [tecnickcom/TCPDF#413]
https://github.com/tecnickcom/TCPDF/blob/main/tcpdf.php#L3318

you have:
`@param string $lw header image logo width in mm`

but:
`$lw=0`

**Comment by williamdes** [comment]
Hi @gemal 
I do not understand where the problem is, could you explain further ?

**Comment by gemal** [comment]
the problem is that the docblock says that `$lw` is a `string` while it's being set to a `int`
A tool like phpstan will complain about this

**Comment by williamdes** [comment]
> the problem is that the docblock says that `$lw` is a `string` while it's being set to a `int`
> A tool like phpstan will complain about this

Oh snap, I missed that
Added a commit for it #402

**Comment by internalsystemerror** [comment]
This is causing the following error since we started incorrectly using a string:
```
TypeError: Unsupported operand types: string * float in file /var/www/vendor/tecnickcom/tcpdf/tcpdf.php on line 3490
Stack trace:
  1. TypeError-&gt;() /var/www/vendor/tecnickcom/tcpdf/tcpdf.php:3490
  2. TCPDF-&gt;Header() /var/www/vendor/tecnickcom/tcpdf/tcpdf.php:3605
  3. TCPDF-&gt;setHeader() /var/www/vendor/tecnickcom/tcpdf/tcpdf.php:3272
  4. TCPDF-&gt;startPage() /var/www/vendor/tecnickcom/tcpdf/tcpdf.php:3184
  ```
