### ISSUE TITLE
sync up functions names for case

### ISSUE THREAD

**Issue by gemal** [tecnickcom/TCPDF#419]
so the function is called `setHeaderData`
https://github.com/tecnickcom/TCPDF/blob/main/tcpdf.php#L3325

but the examples all seems to use: `SetHeaderData`
https://github.com/tecnickcom/TCPDF/blob/main/examples/example_038.php#L41

would be nice if all of the "setXXX" functions where synced up

**Comment by gemal** [comment]
php functions are case insensitive but just for consistency in the project

**Comment by williamdes** [comment]
Good idea, could you make a PR ?

**Comment by gemal** [comment]
what is the correct use?
`setHeaderData` or `SetHeaderData`

I personally vote for `setHeaderData`

**Comment by williamdes** [comment]
`setHeaderData` because it is what the real function name is

**Comment by gemal** [comment]
I've started with the `set` functions
Later on we can look at others like `GetNumChars` functions

**Comment by gemal** [comment]
Let me know on how to proceed. Are they any automated tests?

**Comment by williamdes** [comment]
> Let me know on how to proceed. Are they any automated tests?

There is no tests on this project but all the examples are run on all possible php versions

I bet a tool like phpstan found find out all the non well cased functions isuses.

Best is to create a PR with a commit fixing all the casing of the functions in examples
