### ISSUE TITLE
TCPDF ERROR: Unable to encrypt the file: /tmp/....

### ISSUE THREAD

**Issue by elg0ch0** [tecnickcom/TCPDF#427]
I'm getting the error 

> "TCPDF ERROR: Unable to encrypt the file: /tmp/__tcpdf_da2bc8875a6a06c6630614ae3886e0bb_key_b35ba05eabe95b7419PhNUTd" 

when trying to encrypt my PDF using:

`  $pdf->SetProtection(array('modify'), '12345678', null, 1, array(array('c' => 'file://var/www/tcpdf.crt', 'p' => array('modify'))));
`

- File /var/www/tcpdf.crt exists and it's readable
- Tried empty password and/or master passwd with no success

When trying only the password protected feature it works correctly but it doesn't when adding the encryption part

**tcpdf.crt** was generated running:

`  # openssl req -x509 -nodes -days 365000 -newkey rsa:1024 -keyout tcpdf.crt -out tcpdf.crt
`

I don't find what's wrong... Any suggestions? (there's no extra information in the logs and it seems there's no option to increase the debug level in TCPDF)

**Comment by williamdes** [comment]
Why do you use `file://var/www/tcpdf.crt` and not `/var/www/tcpdf.crt` ?

**Comment by elg0ch0** [comment]
Because of the documentation ([example 016](https://tcpdf.org/examples/example_016/))

```
// Example with public-key
// To open the document you need to install the private key (tcpdf.p12) on the Acrobat Reader. The password is: 1234
//$pdf->SetProtection($permissions=array('print', 'copy'), $user_pass='', $owner_pass=null, $mode=1, $pubkeys=array(array('c' => 'file://../config/cert/tcpdf.crt', 'p' => array('print'))));
```


I tried `/var/tmp/tcpdf.crt` and it didn't work either

**Comment by williamdes** [comment]
Thanks :)
I will try to use the example locally to find out

**Comment by williamdes** [comment]
I would recommend you to change a line in the tcpdf lib to find out

(function _generateencryptionkey)
```diff
- $this->Error('Unable to encrypt the file: '.$tempkeyfile);
+ $this->Error('Unable to encrypt the file: '.$tempkeyfile . ' error: ' . openssl_error_string());
```

Still debugging but some file is not found

**Comment by williamdes** [comment]
Added more debug
```php
					echo 'Temp key file exists: '. (is_file($tempkeyfile) ? 'yes': 'no') . PHP_EOL;
					echo 'Temp enc file exists: '. (is_file($tempencfile) ? 'yes': 'no') . PHP_EOL;
					echo 'Pub key exists: '. (is_file($pubkey['c']) ? 'yes': 'no') . PHP_EOL;
```
All yes and now I have `0909006C:PEM routines:get_name:no start line`

**Comment by williamdes** [comment]
I changed:

```php
'c' => __DIR__ . '/tcpdf.crt',
```
to
```php
'c' => file_get_contents(__DIR__ . '/tcpdf.crt'),
```

And I fall into https://github.com/tecnickcom/tc-lib-pdf-encrypt/issues/4#issuecomment-277826987
And then if I remove the option the PDF is generated

**Comment by williamdes** [comment]
As I am missing some expertise with such functions and from the comment above I did not find anything better maybe you can ask stackoverflow posting the link to my findings, maybe an expert of php encryption would figure out :)

Anyway, from what I posted you will be able to make it work, using file_get_contents and removing PKCS7_DETACHED option

**Comment by elg0ch0** [comment]
@williamdes those are great findings! 

What do you mean by " removing PKCS7_DETACHED option", how can I do that?

**Comment by williamdes** [comment]
Happy to help :)

I mean you have to manually remove ` | PKCS7_DETACHED` from the function `_generateencryptionkey`

https://github.com/tecnickcom/TCPDF/blob/172540dcbfdf8dc983bc2fe78feff48ff7ec1c76/tcpdf.php#L10891

Or find out what causes `PKCS7 routines:PKCS7_dataFinal:unable to find mem bio` but internet does not seem to know

**Comment by elg0ch0** [comment]
got it! I'll try it later today or tomorrow and if everything goes well will change my Dockerfile in order to generate the image accordingly

**Comment by williamdes** [comment]
> got it! I'll try it later today or tomorrow and if everything goes well will change my Dockerfile in order to generate the image accordingly

But please check the file is valid, I did not check and only did see the output show so I assumed the PDF was okay
Happy hacking !

**Comment by elg0ch0** [comment]
> But please check the file is valid, I did not check and only did see the output show so I assumed the PDF was okay
> Happy hacking !

I just validated it, the PDF file is generated properly after changes suggested by @williamdes 
1. Remove PKCS7_DETACHED option
2. Use 'c' => file_get_contents("/var/www/tcpdf.crt")   (indeed, the [openssl_pkcs7_encrypt documentation ](https://www.php.net/manual/en/function.openssl-pkcs7-encrypt.php)does not allow files)

Thanks!

**Comment by icomenezes** [comment]
Eu fiz a mesma coisa mas não consigo abrir o aquivo pdf ; Diz que ele não tem ID que permita isso
