### ISSUE TITLE
Problem wit printing table 

### ISSUE THREAD

**Issue by pnussbaumer** [tecnickcom/TCPDF#448]
I try to create a PDF with TCPDF similar to example 048, but it print no background-color. In the attachment I send the html-cod as string and formated and in a third file I send the code for dreate the PDF. the forth file is the output from tcpdf.
Thanks for your assitance
[bilanz.txt](https://github.com/tecnickcom/TCPDF/files/7491422/bilanz.txt)
[bilanz_html.txt](https://github.com/tecnickcom/TCPDF/files/7491430/bilanz_html.txt)
[bilanz_31.12.2020_pdf.txt](https://github.com/tecnickcom/TCPDF/files/7491431/bilanz_31.12.2020_pdf.txt)
[bilanz_format_html.txt](https://github.com/tecnickcom/TCPDF/files/7491432/bilanz_format_html.txt)

**Comment by pnussbaumer** [comment]
I found the problem!

**Comment by williamdes** [comment]
> I found the problem!

What was it?

**Comment by pnussbaumer** [comment]
It was the wrong declaration, but in the meantime Ihave changed the cod and work with "Cell" and "MultiCell" and so I can better control the printout.
