### ISSUE TITLE
Move all site constants other the db config into the db

### ISSUE THREAD

**Issue by settonull** [tecnickcom/TCPDF#487]
This gives less to track and move between installs.  Also means details are less important (just have to match how you created the local db, don't even need to be the same in different installs).  Will also mean we can administer these settings from the website.

**Comment by settonull** [comment]
whoops wrong github, sorry don't know how to delete

**Comment by settonull** [comment]
I thought that would be possible, but don't see the option too like I do in my own repositories, so assumed I didn't have the necessary permissions.

**Comment by williamdes** [comment]
> I thought that would be possible, but don't see the option too like I do in my own repositories, so assumed I didn't have the necessary permissions.

Yeah this is not possible at an issue level, but on the three dots of a comment you can delete the old revision of it to permanently scrub the data out of it
