### ISSUE TITLE
PDF417 produces wrong output

### ISSUE THREAD

**Issue by bayramarslan** [tecnickcom/TCPDF#488]
![image](https://user-images.githubusercontent.com/2318547/155799797-f2d8e667-8846-4415-bca2-fc4b7ad4846a.png)

PDF417 produces wrong output as above when generating barcode. The php configuration on the server I was working on was as follows.

```apacheconf
[bcmath]
; Number of decimal digits for all bcmath functions.
; http://php.net/bcmath.scale
bcmath.scale = 8
```

For the solution, the scale parameter should be entered as 0 in the `bcmod()` and `bcdiv()` functions.

Barcode value

0348539000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

**Comment by williamdes** [comment]
Same
If it's not fixed keep it open
