### ISSUE TITLE
Package size 

### ISSUE THREAD

**Issue by gdarko** [tecnickcom/TCPDF#520]
The package takes 28mb, is there any way to reduce the size?

**Comment by williamdes** [comment]
> The package takes 28mb, is there any way to reduce the size?

How did you install it ?
You can delete the fonts like we do at phpMyAdmin: https://github.com/phpmyadmin/phpmyadmin/blob/e406ddb13fb66061b195552fc7598a239acaccd0/scripts/create-release.sh#L158

**Comment by gdarko** [comment]
@williamdes thanks for the suggestion. I created a composer script that removes those additional fonts.
