### ISSUE TITLE
This version will not receive any additional development or support?

### ISSUE THREAD

**Issue by smalos** [tecnickcom/TCPDF#545]
"A new version of this library is under development at https://github.com/tecnickcom/tc-lib-pdf and as a consequence this version will not receive any additional development or support. "

This version has still active commits. Please correct the Readme.

**Comment by williamdes** [comment]
See #537
Please close this issue
There is no development, only support :)

**Comment by williamdes** [comment]
But clearly none of the two libraries can be chosen so it's a bit of a complicated situation
One is on very limited and rare support
And the other is not available years later
