### ISSUE TITLE
 TypeError: count() on PHP 8.0.24

### ISSUE THREAD

**Issue by mazuk6** [tecnickcom/TCPDF#555]
Hello,

I ran into this error:
Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in vendor/tecnickcom/tcpdf/tcpdf.php:19718

// for each row
if (count($table_el['trids']) > 0) {
	unset($xmax);
}

by Calling TCPDF->closeHTMLTagHandler() through  TCPDF->writeHTMLCell()

**Comment by NiklasBr** [comment]
Try #556 @mazuk6
