### ISSUE TITLE
Aligned after new page

### ISSUE THREAD

**Issue by tspaolorus** [tecnickcom/TCPDF#558]
Hello,
i have the following problem.
I create the whole document in html and then send it for the creation of the pdf through the command "$ pdf-> writeHTML ($ html, TRUE, FALSE, TRUE, FALSE, '');"
The page jump is done automatically with the command "$ pdf-> SetAutoPageBreak (TRUE, $ margins ['bottom']);".
After the header of the second page, an amount is printed with the alignment on the right. But on the second page, after the header, it is printed at the beginning of the line not using left alignment. The same printed data, not as the first data after the header, is printed and aligned correctly on the right.
Thank 
Paolo

**Comment by williamdes** [comment]
did you find a solution?
