### ISSUE TITLE
Can I use this to fill an existing PDF form?

### ISSUE THREAD

**Issue by Dylan-Buth** [tecnickcom/TCPDF#592]
I've been searching for hours on how to do this and can't find anything other than paying Setasign thousands of dollars. 

I have an existing, fillable PDF form. I'm looking for a way to fill the inputs with data using PHP. I know setasign/fpdi can import PDF forms. Can this package, maybe in conjunction with that one, fill the inputs? 

Has anyone else done this without buying setasign libraries or using iText in Java? Thanks!

**Comment by williamdes** [comment]
If you are trying to edit a PDF this is the wrong project, if you are looking to generate a PDF this is the right project. But there is other open source projects for editing PDFs.
You should ask on StackOverflow and close this issue :)

**Comment by Dylan-Buth** [comment]
I guess filling the inputs counts as editing? Working on SO post now. Thanks!

**Comment by williamdes** [comment]
> I guess filling the inputs counts as editing? Working on SO post now. Thanks!

Yes, but be sure to post the link here so we can follow
