### ISSUE TITLE
deprecated php-function

### ISSUE THREAD

**Issue by avmsone** [tecnickcom/TCPDF#597]
tcpdf.php
line 11001: if (extension_loaded('mcrypt') && mcrypt_get_cipher_name(MCRYPT_RIJNDAEL_128) === false) { ...

mcrypt_get_cipher_name() is deprecated

**Comment by williamdes** [comment]
What does your tcpdf code do?
Does it encrypt?
What tcpdf and php version are you using?

**Comment by avmsone** [comment]
php: 8.1
tcpdf 6.6.2

no I don't encrypt anything in my code. I dont't know why my script uses this part of tcpdf.php.

if I comment out lines 10994-11008 my script works. if not I am notified that mcrypt_get_cipher_name() in line 11001 is deprecated. (https://github.com/tecnickcom/TCPDF/blob/main/tcpdf.php)

sorry, I do not konw more.

**Comment by williamdes** [comment]
https://github.com/tecnickcom/TCPDF/blob/2fb1c01bc37487d1f94fe1297f8d8ad1b5c290bb/tcpdf.php#L11001

Reading the code on this line I think you can close this issue.
As it will be solved if you remove the `mcrypt` module from PHP 8.1 modules list
