### ISSUE TITLE
Use of "self" in callables is deprecated in include/tcpdf_fonts.php (PHP 8.2)

### ISSUE THREAD

**Issue by sagehenstudio** [tecnickcom/TCPDF#632]
An issue with a suggested fix. A "use of "self" in callables is deprecated" warning is arising from tcpdf_fonts.php using PHP 8.2

In lines 1788, 1790, and 2010 of tcpdf_fonts.php, this deprecation warning (PHP 8.2) can be fixed by changing the lines to read:

`return array_map(self::class . "::unichrUnicode",$ta);`

`return array_map(self::class . "::unichrASCII",$ta);` and

`$carr = array_map(self::class . "::uniord",$chars);` respectively.

**Comment by williamdes** [comment]
Hi @sagehenstudio 
Can you open a pull-request for this change ?

**Comment by sagehenstudio** [comment]
Sure: #633
