### ISSUE TITLE
Next TCPDF release ?

### ISSUE THREAD

**Issue by williamdes** [tecnickcom/TCPDF#634]
Hi @nicolaasuni here is a summary of fixes and issues addressed. I intentionally kept some other wrong or unfinished ones from this list.

### PHP 8 fixes

- #632 is fixed by #633
- #630
- #615 fixes #614

### PHP 7 fixes

- #620

### Complex fixes

- #581
- #584

### Nice and small footprint features

- #572

### Important LICENSE fix

- #591

### CI and analysis stuff

- #575
- #613
- #598

### Docs

- #589
- #643 

### CI

- #642 

### Barcode fixes

- #611
- #588 (indentation is broken)

### Workarounds
- #627 (not sure we should accept it, since the function parameter has a type and if it's not respected should we workaround it ?)

**Comment by Hr0bar** [comment]
Thanks for your and all other contributors work keeping this up-to-date with latest PHP versions! Much appreciated by our non-profit NGO where we use it to generate documents.

**Comment by survik1** [comment]
Hi, any chance to get new release? We would especially like to silence all the deprecation/notice errors we get from this library.

**Comment by williamdes** [comment]
> Hi, any chance to get new release? We would especially like to silence all the deprecation/notice errors we get from this library.

What merged bug fixes are them?

**Comment by survik1** [comment]
> > Hi, any chance to get new release? We would especially like to silence all the deprecation/notice errors we get from this library.
> 
> What merged bug fixes are them?

Especially everything under "PHP 8 fixes" would be nice.

**Comment by williamdes** [comment]
6.6.3 is out! (changelog: #643 )
