### ISSUE TITLE
Nothing to see here.

### ISSUE THREAD

**Issue by DuckSportsFan** [tecnickcom/TCPDF#636]
Disregard this thread.

**Comment by DuckSportsFan** [comment]
A simple fix is to change "QRcode()" to "QRcode1()" in: 
phpqrcode/phpqrcode.php:3256
phpqrcode/phpqrcode.php:3270

phpqrcode/qrencode.php:448
phpqrcode/qrencode.php:462

tcpdf_barcodes_2d.php:299

include/barcodes/qrcode.php:265

**Comment by sagehenstudio** [comment]
Seems like you're trying to run an unspecified phpqrcode library along with TCPDF, and there's a conflict because _both_ call the class QRcode. Can I ask why you're running both? Also, why should both libraries change their core to make this integration work, when TCPDF already prints QR codes?

**Comment by DuckSportsFan** [comment]
I believe it is because their code has not been tested in PHP 8 for using "QRCODE,H".  I've been using the library in PHP 8 for 7 months now...7 years in PHP 5.6 - 7.4.  I was using DATAMATRIX, in the past, as a "QR Code", but DATAMATRIX does not work with iPhones built-in camera...So I changed the settings to use QRCODE,H, and the above error gets written to the local error_log.  Your assessment is wrong.  Sorry, but thanks for your opinion.  Notice I fixed "their" code to work already?  Fixed in "their" library?

**Comment by sagehenstudio** [comment]
Using PHP 8.2 with a QRCODE,H in TCPDF works just fine over here.

**Comment by DuckSportsFan** [comment]
Oh! I must have been trying to run an unspecified phpqrcode library along with TCPDF.  My bad.  Never mind.

**Comment by sagehenstudio** [comment]
OK. Please close this issue. Thank you.

**Comment by DuckSportsFan** [comment]
I would, but the issue isn't closed yet.  Thanks for suggesting.  Let's let others participate.  To close this thread with only your suggestion that I don't know the libraries I've loaded into my solution...that I'm loading other unspecified "QRCODE" libraries, is kind of... (you fill in the blanks). BTW - Not bragging here...but I've been programming since 1980.  You?

**Comment by sagehenstudio** [comment]
For anyone coming on after me who might help with this support request, they'll likely ask you a very similar question to the first question I asked you (e.g. what are you doing/trying to do, and why). I was trying to help you with your request for free support (since a fatal error due to a naming conflict is not really an issue with TCPDF), and hopefully you will be a little nicer to the next person.

**Comment by DuckSportsFan** [comment]
For anyone coming on after @sagehenstudio... I'm only using the library furnished by TCPDF and no other library which could possibly be using a function/class name "QRCode".  Again, DATAMATRIX works fine, change DATAMATRIX to QRCODE,H, and it fails...

require_once(dirname(__FILE__).'/tcpdf_include_pass.php');
include('phpqrcode/qrlib.php'); 
bla, bla, bla...
$pdf->write2DBarcode('https://???.org/?x='.$secret, 'DATAMATRIX', 4.8, .5, 1.5, 1.5, $style, 'N');
