### ISSUE TITLE
6.6.4 mistakes

### ISSUE THREAD

**Issue by williamdes** [tecnickcom/TCPDF#644]
See: https://github.com/tecnickcom/TCPDF/commit/31b9389ca69a2d34da3d0d62fbc138c9e45408bf

Can you drop your tag, fix the file and push it back ?

**Comment by nicolaasuni** [comment]
Fixed in the last push. I will tag it later.

**Comment by williamdes** [comment]
Thank you for https://github.com/tecnickcom/TCPDF/commit/3ca051cbdd03fcffa9a8e86ec9cd41541bf5de3a

**Comment by williamdes** [comment]
Oh, 6.6.3 got deleted ?
🤔 https://github.com/tecnickcom/TCPDF/tags

FTR, about tags, maybe it would be worth GPG signing tags: https://github.com/tecnickcom/TCPDF/pull/605#issuecomment-1708447104
