### ISSUE TITLE
ERROR: Uninitialized string offset 52 on line 818 in file /var/www/html/php/vendor/propa/tcpdi/tcpdi_parser.php

### ISSUE THREAD

**Issue by gohelkiran30** [tecnickcom/TCPDF#659]
Getting this warning in log while adding a pdf file as template
ERROR: Uninitialized string offset 52 on line 818 in file /var/www/html/php/vendor/propa/tcpdi/tcpdi_parser.php

```
        $this->AddPage();

        $this->setSourceFile(__DIR__ . 'PDF_FILE_HERE.pdf');

        $idx = $this->importPage(1);

        $this->useTemplate($idx);
```

**Comment by sagehenstudio** [comment]
You are seeking help for TCPDI in the TCPDF pages. They are different repositories with different authors.

Maybe head over to https://github.com/pauln/tcpdi to post your issue there, instead. 😊

**Comment by williamdes** [comment]
Good catch, indeed
You should definitely close this issue here

Also, I am pretty sure this my be wrong:
`__DIR__ . 'PDF_FILE_HERE.pdf'`

Use
`__DIR__ . '/PDF_FILE_HERE.pdf'`

**Comment by gohelkiran30** [comment]
Ok, moved to tcpdi repo
https://github.com/pauln/tcpdi/issues/28
