### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class "Com\Tecnick\Pdf\ClassObjects" not found

### ISSUE THREAD

**Issue by apasho** [tecnickcom/TCPDF#730]
I manually installed the TCPDF library from the zip file and require_once the Tcpdf.php. I also require_once all the other files in the src folder but got the same issue.

**Comment by littlepackage** [comment]
Can you be more specific about which "all other files" you are requiring, and which src folder? There is no src folder in the TCPDF zip package, and nothing in the package that would call a ClassObjects class. Please show _your_ code, thanks.

**Comment by apasho** [comment]
I switched to a different library two months ago.

**Comment by apasho** [comment]
This is no longer an active issue.
